### ISSUE TITLE
Cloud: Bugs on importing images from RTMI

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#102]
Please see list below:

- Only a partial section of the image is being shown. Need to see the entire image. See below

![image](https://cloud.githubusercontent.com/assets/5666297/12620177/2555f194-c4e9-11e5-9f1b-b1d3ba0a7627.png)

- After importing 2 images and going back to import more, getting the following message. It should still allow more images to be imported.

![image](https://cloud.githubusercontent.com/assets/5666297/12620260/9f1d81cc-c4e9-11e5-84a8-8634b7557b91.png)

- When user presses import, can you please add a "Importing Images..." message so that the user knows that something is happening ?

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Please see below screenshots:

Complete images displayed in preview:

![image](https://cloud.githubusercontent.com/assets/13255706/12640734/57796c52-c5cd-11e5-8173-8aefcdc2a397.png)

Loader applied while uploading images:

![image](https://cloud.githubusercontent.com/assets/13255706/12640772/869f2332-c5cd-11e5-835b-41b67feb6034.png)

The 'No RTMI exists...' message will not be displayed now. If the user attempts to import more images to the same labour, the application will allow him to do so.
Please note that we have applied a loader instead of displaying the "Importing Images..." message to retain the loading format consistency throughout our application.

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Giovani to re-test.

**Comment by giovanicani** [comment]
works. just a bit slow to import images but works. will monitor.
