### ISSUE TITLE
Cloud: Email is not showing correct FROM

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#104]
See below, we discussed this already:

Screen shows one thing...
![image](https://cloud.githubusercontent.com/assets/5666297/12621207/818391e8-c4ed-11e5-9531-9e2cea333b68.png)

Actual email shows something else...
![image](https://cloud.githubusercontent.com/assets/5666297/12620835/e5ecc282-c4eb-11e5-955d-48570cdaa80b.png)

**Comment by giovanicani** [comment]
On  Gmail, the email above should read:

```
From:  Giovani Cani <gcani@trailcon.com>
reply-to:  Giovani Cani <gcani@trailcon.com>
to: Giovani Cani <giovani.cani@gcso2.com>
cc:
[hidden] bcc: notifications@trailcon.com
date: good as is
subject: good as is
signed-by: trailcon.com
```

**Comment by d3sqa** [comment]
@giovanicani, there is an issue if we set the From email address with actual From address of a user. The email won't be sent in this scenario.

See screenshot below:

![new111111](https://cloud.githubusercontent.com/assets/13255706/12642749/950b02e0-c5d9-11e5-8f33-7054d3a05db4.png)

However, if we place 'operationsgroup@trailcon.com' in the From and just display the user's email address with it, it works fine and the email is sent successfully.

Can you please provide your feedback on this?

**Comment by giovanicani** [comment]
Gene to talk to Erik about being able to remove the operationsgroup@trailcon.com from the FROM and make it so that is nreid@trailcon.com.

**Comment by TeqdirectGene** [comment]
Giovani:  Erik has gone back and forth with you re this issue: Do you feel we have resolved it?  thanks, gene

**Comment by d3sqa** [comment]
Please check the screenshot below. Ready to test.

![image](https://cloud.githubusercontent.com/assets/13255706/12667081/f6ccbc6e-c668-11e5-8b17-466744e33bcd.png)

**Comment by giovanicani** [comment]
Looks better. 

Can you please do a negative test where the email server is down (or invalid) make sure that the user gets a proper message saying that email was not sent ?

This feedback to the user is important. Thanks.

**Comment by d3sqa** [comment]
@giovanicani, we are displaying a generic message when the email is not sent. A few example scenarios in which email could not be sent are:

1. Internet not working
2. Email server is down
3. Sender is invalid (Non trailcon domain)
4. Incorrect username/password

Check screenshot below:

![newwwwwwwwwwwwww](https://cloud.githubusercontent.com/assets/13255706/12694398/8de91990-c74e-11e5-82c8-569e6b948e4c.png)

Whenever the API is down, we are displaying following message:

![screenshot_58](https://cloud.githubusercontent.com/assets/13255706/12694400/a17aa3f2-c74e-11e5-927b-0f22abdb9e7f.png)

Are you ok with the generic messages ?

Because if we display server's response, the end user won't be able to understand it. Below is the screenshot of message displayed in case the sender is invalid:

![image](https://cloud.githubusercontent.com/assets/13255706/12694409/dbd4be8e-c74e-11e5-8707-6b72ce9fc37e.png)

**Comment by giovanicani** [comment]
Thanks Guys, these generic message are good enough.
