### ISSUE TITLE
Cloud: Wrong Message when quoted hours is blank

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#130]
Wrong Message when quoted hours is blank.

Message should be: **Labour line(s) xxxxx,xxxx,xxxx don't have customer quoted hours.**

![image](https://cloud.githubusercontent.com/assets/5666297/12830868/73a269a0-cb5f-11e5-9c63-7dfd7d0dd4cc.png)

**Comment by d3sqa** [comment]
@giovanicani, we have a priority set over here. Following is the priority from highest to lowest:

1. When Part without a Part # exists
2. When labour doesn't have parts
3. When Quotes hours are null
4. When Qty or Charge $ is null

The reason why the above message was prompted in case when Quoted Hrs are null is because the labour didn't have parts associated (which is a high priority) message

Also, do we need to change the message when quoted hrs are null to the one written above ? Because currently we display "There are parts without Quoted quantity and/or Charge $"

**Comment by d3ssupport** [comment]
Link with #117.

**Comment by giovanicani** [comment]
Not working as discussed.

**Comment by giovanicani** [comment]
working
