### ISSUE TITLE
Cloud: Add time component on the Quote Date

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#14]
Add time component.

![image](https://cloud.githubusercontent.com/assets/5666297/11850734/30cbdda2-a3fd-11e5-8d9f-c8eae712b5eb.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Time component has been added at the Date column of the Quote Listing grid. The fix is available in the development environment and will be available at the UAT Environment after the deployment of the upcoming release

![image](https://cloud.githubusercontent.com/assets/13255706/11868691/8a2357e8-a4db-11e5-920c-30bf2e9a4153.png)

**Comment by giovanicani** [comment]
looks good thanks!
