### ISSUE TITLE
Cloud: Grant Access on Production

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#145]
For Reefer Approval & Quote Close: Kelly da Gloria, Jon Drohan

For Quote Close: Natalya and Colleen

For Trailer Approval and Quote Close: John Dejong and Paul Couture

Thanks!

**Comment by giovanicani** [comment]
Also to Peter - Approval Reefer, Approval Trailer.
Shawn - Approval Reefer, Approval Trailer.

**Comment by d3sqa** [comment]
Access rights have been granted to the following users (At Prod):

For Reefer Approval & Quote Close: Kelly da Gloria, Jon Drohan
For Quote Close: Natalya
For Trailer Approval and Quote Close: John Dejong and Paul Couture

For the following users, please let us know the full names so that we could grant the rights accordingly:

![image](https://cloud.githubusercontent.com/assets/13255706/12913717/37739cd8-cf42-11e5-9933-6dbddf3e6562.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12913721/40d7413a-cf42-11e5-8896-b721ec8c6e14.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12913730/4cc13f5a-cf42-11e5-9aa0-7b689bf96552.png)

**Comment by d3sqa** [comment]
Please make sure to logout and then log in again to get this working

**Comment by giovanicani** [comment]
ok thanks!
