### ISSUE TITLE
Cloud: Why Reefer / Trailer become disabled after Quote Save

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#147]
When did this change ??

Why the 2 check box become read only now ? Status is quote started and user cannot change the checkbox.

![image](https://cloud.githubusercontent.com/assets/5666297/12920955/fb67d87c-cf18-11e5-9503-d6a5609b7b10.png)

**Comment by d3sqa** [comment]
The Reefer/Trailer flags will now be enabled for all users. Grant access is also functional now. Ready to test in UAT Environment

For the following users, please let us know the full names so that we could grant the rights accordingly:

![image](https://cloud.githubusercontent.com/assets/13255706/12946395/e929d5e0-d015-11e5-89a6-7d6cfd454c66.png)

**Comment by giovanicani** [comment]
Thanks!

Users are: cc002, po002, sf001

**Comment by giovanicani** [comment]
please do UAT and PROD.

**Comment by d3sqa** [comment]
Done at both UAT and PROD
