### ISSUE TITLE
Cloud: Edit Part not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#7]
Edit part not working, cannot update quantity or part number. Buttons are incorrect, etc...

** Entire popup part screen not functional **

![image](https://cloud.githubusercontent.com/assets/5666297/11849819/cc67e036-a3f7-11e5-84a7-6ee750792b02.png)

**Comment by d3sqa** [comment]
Edit part feature is now incorporated at the edit quote form. Done in development environment

**Comment by giovanicani** [comment]
On insert quote form... user need to be able to also update part / labour / etc...

On edit quote form... works better but still has bugs, see sequence of screen shots below... user is never able to update part U80795 ... when double clicking another or no part shows up.

![image](https://cloud.githubusercontent.com/assets/5666297/12042031/f3eeda72-ae44-11e5-9936-38dbea5c53f3.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12042034/fe59657c-ae44-11e5-98a2-e3759f7d490d.png)

**Comment by giovanicani** [comment]
please provide update.

**Comment by giovanicani** [comment]
Why am I getting this message ?

![image](https://cloud.githubusercontent.com/assets/5666297/12097600/7226b9a6-b2ea-11e5-92b7-1fc0a05f16e4.png)


Notes should not be mandatory.

**Comment by d3sqa** [comment]
Part # mandatory check has been removed in case of existing part selected from the grid. The check will remain in place in case a new part (without part #) is added by the user. 
At Add/Edit Quote, the part editing feature has been incorporated. Ready to test in development environment

Please note that part notes are not displayed at the Add Quote form currently. Work in progress on that.
One more thing is remaining while editing parts, the scenario is below:

1. Select and add part from the grid
2. Click Clear button so that part selection is removed
3. Now write part description and click update (Attempt to add a part without part #)
4. The existing part (Previously added) would remain in place and will not be overwritten by a new one

Work in progress on this scenario at both Add Quote and Edit Quote

**Comment by d3sqa** [comment]
The selected part is now highlighted at Add Quote form

![image](https://cloud.githubusercontent.com/assets/13255706/12142108/51e4e9ac-b497-11e5-8d3f-76dab905d17c.png)

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
added my parts comments on the labour issue thread. will close this one.
